version: '3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  app:
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    restart: always