version: "3"
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    networks:
      - net
  app:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
    networks:
      - net
networks:
  net: